# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQ1Kt0WoB2chJKWf1BOuh8qgG6L5Ig8C
"""

# ============================================================
# Bangladesh Air Quality Monitoring System
# Sentinel-5P (TROPOMI) + Google Earth Engine
# ============================================================

import streamlit as st
import ee
import geemap.foliumap as geemap
import pandas as pd

# ------------------------------------------------------------
# Initialize Earth Engine
# ------------------------------------------------------------
import ee

ee.Initialize(project="ee-mukarrammee")


# ------------------------------------------------------------
# Streamlit Page Setup
# ------------------------------------------------------------
st.set_page_config(
    page_title="Bangladesh Air Quality Monitoring System",
    layout="wide"
)

st.title("🇧🇩 Bangladesh Air Quality Monitoring System")
st.markdown(
    """
Satellite-based air quality analysis using **Sentinel-5P (TROPOMI)**
Data source: **Copernicus / Google Earth Engine**
"""
)

# ------------------------------------------------------------
# Administrative Boundaries
# ------------------------------------------------------------
country = (
    ee.FeatureCollection("FAO/GAUL/2015/level0")
    .filter(ee.Filter.eq("ADM0_NAME", "Bangladesh"))
)

districts = (
    ee.FeatureCollection("FAO/GAUL/2015/level2")
    .filter(ee.Filter.eq("ADM0_NAME", "Bangladesh"))
)

# ------------------------------------------------------------
# Sidebar Controls
# ------------------------------------------------------------
st.sidebar.header("Settings & Parameters")

pollutant = st.sidebar.selectbox(
    "Select Air Pollutant",
    ["NO2", "SO2", "CO", "Aerosol Index"]
)

year = st.sidebar.selectbox(
    "Select Year",
    list(range(2019, 2026)),
    index=5 if 2024 in range(2019, 2026) else 0
)

month = st.sidebar.selectbox(
    "Select Month",
    list(range(1, 13)),
    index=0
)

# ------------------------------------------------------------
# Sentinel-5P Configuration
# ------------------------------------------------------------
POLLUTANTS = {
    "NO2": {
        "collection": "COPERNICUS/S5P/OFFL/L3_NO2",
        "band": "tropospheric_NO2_column_number_density",
        "vis": {
            "min": 0.0,
            "max": 0.0002,
            "palette": ["black", "purple", "blue", "cyan", "green", "yellow", "orange", "red"]
        },
        "unit": "mol/m²"
    },
    "SO2": {
        "collection": "COPERNICUS/S5P/OFFL/L3_SO2",
        "band": "SO2_column_number_density",
        "vis": {
            "min": 0.0,
            "max": 0.0005,
            "palette": ["black", "blue", "cyan", "green", "yellow", "red"]
        },
        "unit": "mol/m²"
    },
    "CO": {
        "collection": "COPERNICUS/S5P/OFFL/L3_CO",
        "band": "CO_column_number_density",
        "vis": {
            "min": 0.0,
            "max": 0.05,
            "palette": ["black", "blue", "green", "yellow", "orange", "red"]
        },
        "unit": "mol/m²"
    },
    "Aerosol Index": {
        "collection": "COPERNICUS/S5P/OFFL/L3_AER_AI",
        "band": "absorbing_aerosol_index",
        "vis": {
            "min": -1,
            "max": 4,
            "palette": ["blue", "white", "yellow", "orange", "red", "brown"]
        },
        "unit": "index"
    }
}

# ------------------------------------------------------------
# Load Sentinel-5P Image
# ------------------------------------------------------------
def load_pollutant(year, month):
    cfg = POLLUTANTS[pollutant]
    start = ee.Date.fromYMD(year, month, 1)
    end = start.advance(1, "month")

    img = (
        ee.ImageCollection(cfg["collection"])
        .filterDate(start, end)
        .filterBounds(country)
        .select(cfg["band"])
        .mean()
        .clip(country)
    )

    return img

image = load_pollutant(year, month)

# ------------------------------------------------------------
# Map Visualization
# ------------------------------------------------------------
m = geemap.Map(center=[23.7, 90.3], zoom=6)

m.addLayer(
    image,
    POLLUTANTS[pollutant]["vis"],
    f"{pollutant} ({month}/{year})"
)

m.addLayer(
    country.style(color="white", fillColor="00000000", width=2),
    {},
    "Bangladesh Boundary"
)

m.add_colorbar(
    POLLUTANTS[pollutant]["vis"],
    label=f"{pollutant} ({POLLUTANTS[pollutant]['unit']})"
)

m.to_streamlit(height=650)

# ------------------------------------------------------------
# District-Level Statistics
# ------------------------------------------------------------
st.subheader("📊 District-level Statistics")

stats = image.reduceRegions(
    collection=districts,
    reducer=ee.Reducer.mean(),
    scale=1000
)

def ee_to_df(fc):
    features = fc.getInfo()["features"]
    rows = []
    for f in features:
        row = f["properties"]
        rows.append(row)
    return pd.DataFrame(rows)

df = ee_to_df(stats)
df = df.rename(columns={"mean": f"{pollutant}_mean"})
df = df[["ADM2_NAME", f"{pollutant}_mean"]].dropna()

st.dataframe(df, use_container_width=True)

# ------------------------------------------------------------
# CSV Export
# ------------------------------------------------------------
csv = df.to_csv(index=False).encode("utf-8")

st.download_button(
    label="⬇️ Download District Statistics (CSV)",
    data=csv,
    file_name=f"Bangladesh_{pollutant}_{year}_{month}.csv",
    mime="text/csv"
)

# ------------------------------------------------------------
# Scientific Notes
# ------------------------------------------------------------
st.markdown(
    """
### ⚠️ Scientific Notes
- Sentinel-5P measures **tropospheric column density**, not direct ground-level concentration.
- Results are affected by cloud cover and atmospheric conditions (especially during monsoon).
- Suitable for **spatio-temporal pattern analysis**, trend detection, and comparative studies.
"""
)

